### ISSUE TITLE
Publishing to NPM

### ISSUE THREAD

**Issue by hardillb** [kpavel/node-red-node-openwhisk#13]
If the node is not ready for people to use please don't publish it to npm it just confuses people.

If you want people to test the node they can do a npm from git with the following syntax:

```
npm install kpavel/node-red-node-openwhisk
```

Or at least remove the node-red from the keywords so it doesn't show up on flows.nodered.org

**Comment by hardillb** [comment]
Also rather than fork the openwhisk nodes have you considered contributing to the orginal node?

**Comment by glikson** [comment]
@hardillb it is 'ready-enough' to make it somewhat discoverable. didn't know about the option to install from github - thanks! will consider it. We do consider contributing the changes back.
