### ISSUE TITLE
Error: local docker client not initilized

### ISSUE THREAD

**Issue by nagarashish** [kpavel/node-red-node-openwhisk#19]
When I add a openwhisk action to run in local container, I get "local docker client not initilized" error.  If I restart the node-red container, local container start and openwhisk action executes locally.  What am I doing wrong?

![ow_localerror](https://cloud.githubusercontent.com/assets/4293310/26617940/9546a460-45f5-11e7-9d64-e41640f8e3c1.png)

**Comment by glikson** [comment]
Hi @nagarashish - thanks for checking this out!
We are in the process of deprecating this repo in favor of https://github.com/kpavel/openwhisk-light - which would provide pretty much the same functionality with standard (unmodified) OpenWhisk nodes in Node-RED (you just need to deploy openwhisk-light in another container, and specify the URL of the local openwhisk-light runtime in the action node configuarion -- .e.g, http://172.21.0.1:3000/api/v1 - with your "normal" auth key to access OpenWhisk). Would you mind switching to that one?

**Comment by nagarashish** [comment]
thanks. I will to new repo.
